### ISSUE TITLE
type error and fail to start the project locally run docker-compose build && docker-compose up

### ISSUE THREAD

**Issue by jzsplk** [Multiwoven/multiwoven#451]
**Describe the bug**
```
src/components/ModelTable/ModelTable.tsx(19,11): error TS2322: Type 'Promise<APIData>' is not assignable to type 'ApiResponse<GetAllModelsResponse[]> | Promise<ApiResponse<GetAllModelsResponse[]>>'.
7.895   Type 'Promise<APIData>' is not assignable to type 'Promise<ApiResponse<GetAllModelsResponse[]>>'.
7.895     Property 'status' is missing in type 'APIData' but required in type 'ApiResponse<GetAllModelsResponse[]>'.
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 2
```
**To Reproduce**
1. run `docker-compose build && docker-compose up` on  local

**Expected behavior**
server should run 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos Sequoia 15.0.1

**Additional context**
use colima on mac

**Comment by xyfer17** [comment]
the above issue occur after the merge of commit --> https://github.com/Multiwoven/multiwoven/commit/7084f65443a07062edbe874df96a1159bbae1367

```
7084f65443a07062edbe874df96a1159bbae1367 is the first bad commit
commit 7084f65443a07062edbe874df96a1159bbae1367
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Tue Oct 22 16:35:04 2024 +0530

    feat(CE): added new pagination format
```

issue cause by the change in file --> [‎ui/src/components/ModelTable/ModelTable.tsx](https://github.com/Multiwoven/multiwoven/commit/7084f65443a07062edbe874df96a1159bbae1367#diff-6f0f6c8141cb3895231a786283ea069ac1132c5eded2c0faa9cababbc8a2649e)

![Screenshot 2024-11-02 at 12 13 26 PM](https://github.com/user-attachments/assets/22784217-87c0-4309-86c0-f840c96ecbd8)

**Comment by macintushar** [comment]
Hi @jzsplk, please check if this issue is still happening. We have fixed the UI build.

// @Mohith93

**Comment by subintp** [comment]
closing due to inactivity.
